//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrakrikaUP04._01.appData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Payment = new HashSet<Payment>();
        }
    
        public int Employee_id { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Middle_name { get; set; }
        public Nullable<System.DateTime> Birth_date { get; set; }
        public Nullable<int> Phone_number { get; set; }
        public Nullable<System.DateTime> Employment_date { get; set; }
        public Nullable<int> Position_id { get; set; }
    
        public virtual Employee_class Employee_class { get; set; }
        public virtual Position Position { get; set; }
        public virtual Employee_Subject Employee_Subject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payment { get; set; }
    }
}
