//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrakrikaUP04._01.appData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_class
    {
        public int employee_id { get; set; }
        public Nullable<int> class_id { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
