//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrakrikaUP04._01.appData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database1Entities : DbContext
    {
        public Database1Entities()
            : base("name=Database1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Class> Class { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Employee_class> Employee_class { get; set; }
        public virtual DbSet<Employee_Subject> Employee_Subject { get; set; }
        public virtual DbSet<Payment> Payment { get; set; }
        public virtual DbSet<Position> Position { get; set; }
        public virtual DbSet<Subject> Subject { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
