//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrakrikaUP04._01.appData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Payment_id { get; set; }
        public int employee_id { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
        public Nullable<decimal> amount { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
